C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L\AGCUO5M1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L\AHMYOPM1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L\AYFUOPM1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L\BW1XSDWO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L\K43VQFQT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0105df60\LEDMRE1L\LJ3BRVQT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L\EIQQZLG1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L\F5QMZLG1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L\VXMKEWTQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L\WPUHRHS1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L\X2MGIXS1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\08d80067\ME1FRG1L\X3F0IXS1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI\C5FVCTPY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI\DP33F3CV
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI\NW0G2DEH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI\UN3GWQZH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI\USUKWQZH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0bbfa4a3\EZLBRELI\UT0GWAZH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76\DIDXRELP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76\DIDXRELP\K2YIBA2T
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76\DIDXRELP\PMZBYQ2T
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76\DIDXRELP\SG35FFSV
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76\DIDXRELP\VTJUSIM0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0e4d9b76\DIDXRELP\VXHYSYM0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK\JQU0MQDD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK\JT4Z22UD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK\JUBR1INJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK\UK1QY42A
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK\ULV2YO2A
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0f47322b\MI0VRGTK\UU2QYO2A
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\0CYCTZIY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\0DR4TZIY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\1QJ5KJIY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\BCCJGW41
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\C00UNBMK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\CZWUNRMK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\0fd514fc\J00AJDB2\HLDFGG41
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5\AHIZWHDD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5\BTMUVMYP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5\CQMMV2YP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5\J3M24MOR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5\JCFQ4MOR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\11c00f1d\JS03JDZ5\JDL242OR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K\4KZ4RHFR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K\KCLPF1Y4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K\LGONO53D
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K\LHABOP3D
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K\LZHBO53D
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\124772d6\KYDHRG1K\Z4IHDPSU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9\WVTMRELM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9\WVTMRELM\BS2V5003
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9\WVTMRELM\JAZQNPFW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9\WVTMRELM\JOQMNPFW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9\WVTMRELM\Q3SO4CR4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\12c1b0f9\WVTMRELM\RZTG5SR4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP\BNYEOD40
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP\GMVTEEO2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP\GMYUOD40
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP\ZGD0ZQZI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP\ZYE0ZAZI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\1b71cbc1\CUDBRGTP\ZZKWZQZI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad\MDKTRGDM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad\MDKTRGDM\SM5F3B0M
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad\MDKTRGDM\SM5R3B0M
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad\MDKTRGDM\VG15YCCS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad\MDKTRGDM\YLG4VGMH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\21556cad\MDKTRGDM\YPISVWMH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE\JHJTSQ3A
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE\M2YUCOPZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE\M3WYC4PZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE\MC5UC4PZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE\WN3RK5Q1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\218dfc1f\OHCQRFDE\XO3NLPQ1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI\2LDDMFPY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI\2UKPMFPY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI\2VEDMVPY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI\2XMPIB0F
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI\J31RDDHZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\25cfd6e7\OEPDRFTI\PK1FDDHZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH\0B4ZED5V
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH\2MD1KPYC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH\2SE1K5YC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH\2TKXKPYC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH\305JED5V
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\26737d04\TEHORGDH\Z2Y15RGF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103\E5GEQK1K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103\E5GEQK1K\MJMSFVOO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103\E5GEQK1K\NVYS2FOO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103\E5GEQK1K\RF2G5DSX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103\E5GEQK1K\WY2G5DSX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2a6ad103\E5GEQK1K\X1345DSX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308\MAB2QKDJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308\MAB2QKDJ\RAUGCMIA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308\MAB2QKDJ\RFUGCMIA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308\MAB2QKDJ\SXUSCMIA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308\MAB2QKDJ\XXUKCMIA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2b786308\MAB2QKDJ\XYUGCMIA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a\NLKVRE1E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a\NLKVRE1E\B22LFNUY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a\NLKVRE1E\LPYOARS3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a\NLKVRE1E\P3Y0ARS3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a\NLKVRE1E\PSY0C5YW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\2d08555a\NLKVRE1E\PWWWCPYW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f\C1SRRE1P
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f\C1SRRE1P\FZHTUC3R
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f\C1SRRE1P\IITONXSD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f\C1SRRE1P\IM3CNHSD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f\C1SRRE1P\M52R00GT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\31aeff0f\C1SRRE1P\N32F00GT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM\HILZB55Y
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM\HJFVBP5Y
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM\HXCVB55Y
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM\TDT45CR4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM\TOTO5CR4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\33c55881\LLPARFDM\Z53WJOKF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K\3WL50CDN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K\QKFMEXN0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K\QLLAEHN0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K\QVMAEXN0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K\ST5B22EZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\36c22d03\BHLERE1K\WM5V3MEZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ\5WRZYYLF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ\IYORY2RC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ\MO1VAASR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ\MPVZAQSR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ\MQ2VAQSR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\38d6ea7f\JHGVQKDJ\OJSN4SV3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI\ABYJZEH0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI\GRZFZEH0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI\NOK1ACS5
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI\YONPBG31
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI\YPDDBW31
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\39f9ae62\SQSVRFTI\YREDBG31
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde\KTS5REDL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde\KTS5REDL\2HW2TTSK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde\KTS5REDL\2LYQTDSK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde\KTS5REDL\EDZN4R1N
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde\KTS5REDL\H3CTBDMR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\3d5a8bde\KTS5REDL\UQHCAP5H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\5E04EDII
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\5H04EDII
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\T3YNICS1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\UHJO5TBR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\ULYNICS1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\V13OGDBR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4452d959\UVWHQILI\V5VKGDBR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK\2JCC3YSX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK\2WLO3YSX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK\2XFC3ISX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK\C3QZBCG5
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK\CJ1SHRSZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4675e8d7\UV1ORGTK\EORJBCG5
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df\IACSRF1M
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df\IACSRF1M\3GM0E5XG
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df\IACSRF1M\CCLLKGI0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df\IACSRF1M\CYTHKGI0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df\IACSRF1M\MDQSQL5V
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\46b6b0df\IACSRF1M\PBQCQL5V
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H\1P4RU3UF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H\FR2L4TFF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H\Q23QZHDS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H\QC0QZXDS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H\QDU2ZHDS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\47e2b3f1\CE1MRG1H\ZS5NU3UF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG\0BD2Q2GR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG\0ID2Q2GR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG\5MCIQ2GR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG\WC0SVA22
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG\WGSWVA22
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\49af368e\IBW2QILG\X0GWMQ22
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J\U30OFREE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J\V3I52X2H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J\VADTNNAV
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J\VCBT2X2H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J\VDP52H2H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4b2ae7df\DECTRG1J\XN1GABEE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4fbec240\GA1JXMTI\JOGT2EB4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4fbec240\GA1JXMTI\P0HL2EB4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4fbec240\GA1JXMTI\PBGT2EB4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\4fbec240\GA1JXMTI\PTGT2EB4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E\04NRF5VC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E\5PIKQ5UB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E\TGYQGJ2E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E\THW2GZ2E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E\TY5QGZ2E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\513b4145\KBTXRF1E\YAJCQPUB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2\35RVAUKD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2\3AYZAUKD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2\3BWVAEKD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2\I1NMXRRR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2\KYM2XRRR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\51f582d4\TRSPJCR2\MF0FXHIJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48\NNOSQKTM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48\NNOSQKTM\0TJU12QA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48\NNOSQKTM\33JY12QA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48\NNOSQKTM\CAHRDWZN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48\NNOSQKTM\VJVYAIAS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\52a2ab48\NNOSQKTM\VN1UAYAS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0\SJPORFDK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0\SJPORFDK\2LRQDH34
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0\SJPORFDK\2P52DX34
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0\SJPORFDK\4CTOLG5W
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0\SJPORFDK\FPK4JM0S
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\5c7708a0\SJPORFDK\ZISGOW5W
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e\SFKPJCZ3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e\SFKPJCZ3\0LJF41YX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e\SFKPJCZ3\1OJV41YX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e\SFKPJCZ3\AEYBACNT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e\SFKPJCZ3\AI22G2JN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\614d830e\SFKPJCZ3\AMSQGMJN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP\2LIBENMO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP\2PAFENMO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP\3TUF33MO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP\AXR0ZPFW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP\D0QOZPFW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\61a0a777\VJWMQIDP\D3QOZPFW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK\40TQLAFT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK\F2JNNHTM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK\F3HBNXTM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK\FDABNHTM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK\FZWSIU0J
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\64d27997\I5S4RGDK\ZDTALAFT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9\AYJUQKDL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9\AYJUQKDL\VV4X23MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9\AYJUQKDL\WU4123MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9\AYJUQKDL\WW4523MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9\AYJUQKDL\XT4X23MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\65f7cdf9\AYJUQKDL\XU4X23MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI\LKRA2GBE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI\LUWA2WBE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI\LVYM2GBE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI\S21WCREE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI\UR1GCREE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6a7cab6a\FF0TRGTI\VAC1IN2V
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K\4KXOYY3O
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K\5SLKBI3O
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K\5WDOBI3O
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K\WBIJAN4F
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K\WMJ3AN4F
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6e1784d7\DLGUQK1K\WRJ3AN4F
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904\WBXBRGDE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904\WBXBRGDE\0NYG1ZDV
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904\WBXBRGDE\FE35FIH4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904\WBXBRGDE\PJQLIPIL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904\WBXBRGDE\PN4HI5IL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\6ff9d904\WBXBRGDE\RRCZ3L1J
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32\UZXCRGDN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32\UZXCRGDN\2Z332H4P
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32\UZXCRGDN\3N2J2H4P
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32\UZXCRGDN\IYCDTCGM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32\UZXCRGDN\QKA0Z3QO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\77e10e32\UZXCRGDN\QOOWZNQO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c\NLRRQIDK
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c\NLRRQIDK\LA5JGIWO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c\NLRRQIDK\MB0SROJH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c\NLRRQIDK\NXOSI4JH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c\NLRRQIDK\U1QCWVSP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\781c605c\NLRRQIDK\U4QCWVSP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM\3QMMLYHU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM\5132FX2W
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM\5EUQFX2W
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM\5F02FH2W
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM\DNTZIQUU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79408454\MDKXRFTM\HJQL0MFE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW\CMD5WT15
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW\EDDPWT15
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW\IHCYJLMH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW\K4T5OMP1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW\KAU5O2P1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\79efb594\JVCOJDZW\KB0TOMP1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023\O3TERF1P
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023\O3TERF1P\545OSYU3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023\O3TERF1P\5T4CSIU3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023\O3TERF1P\PAR24IZN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023\O3TERF1P\PE5Q4YZN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\83f39023\O3TERF1P\SMPXZP3S
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\CVTEREDL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\CVTEREDL\03QCZFYR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\CVTEREDL\DPC2SA55
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\CVTEREDL\DRF2SQ55
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\CVTEREDL\OP1SE4SB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\WQ0QRF1K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\WQ0QRF1K\3TJW4XTD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8e74b56e\WQ0QRF1K\PORMEA4A
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N\E0PT3X5E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N\EEIT3H5E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N\EFG53X5E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N\FRIYPUBB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N\LOS3Q52R
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fb88b3e\M2DMRF1N\OURI14K2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fd43684\EI1BRFTM\RG442I4G
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\8fd43684\EI1BRFTM\RZXS2I4G
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P\1IRO44MB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P\1J5C4OMB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P\1XYC44MB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P\2B5C0IGH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P\3P5W5YGH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\90db0ae6\DPKQRG1P\RGEL0OJQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d\EYZFQILN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d\EYZFQILN\01KGNLMD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d\EYZFQILN\1QLGM1MD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d\EYZFQILN\4LLGM1MD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d\EYZFQILN\IAJY5ZSC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\91fea19d\EYZFQILN\Z1LGM1MD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L\435EGLY1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L\GQUZKRIL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L\HCFETBIL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L\HDMYTBIL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L\W05T1VP4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\92f4f8b6\SVO4QI1L\Z35UGLY1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL\02IMGS3F
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL\04KBAVMF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL\41JAGS3F
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL\ZOSZCZ3K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL\ZQVZCJ3K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\94ac3218\TIDVRGTL\ZU1VCZ3K
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\9e9f9072\MYBSQKDH\BAYNJ4U2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\9e9f9072\MYBSQKDH\BJYNJ4U2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\9e9f9072\MYBSQKDH\WSIWSDHO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\9e9f9072\MYBSQKDH\WXASSDHO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\9e9f9072\MYBSQKDH\XBUSLTHO
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\9e9f9072\MYBSQKDH\XDDKL2UC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH\13E3KION
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH\1CNRKION
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH\1DD3KYON
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH\A2SOVEZL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH\BDS4VEZL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a028fec4\VETUREDH\CHV4NPCZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25\DHTRRFTJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25\DHTRRFTJ\NLSYSR2Z
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25\DHTRRFTJ\NP2USB2Z
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25\DHTRRFTJ\O4AZQGRY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25\DHTRRFTJ\XQNQZ1QV
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a410eb25\DHTRRFTJ\XTNEZ1QV
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H\5ORWC5YT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H\5QWWCPYT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H\5RY0C5YT
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H\B2MTHNMY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H\NPZOGRS3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\a7072065\PLK4RF1H\OTY4GRS3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3\CVLVRE1P
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3\CVLVRE1P\ILVGSYD3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3\CVLVRE1P\IP1KSID3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3\CVLVRE1P\KB3WPSA4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3\CVLVRE1P\QDSV3SCS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ac7d60a3\CVLVRE1P\TOSZ3SCS
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab\OJSTRFTP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab\OJSTRFTP\3E2GH345
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab\OJSTRFTP\DQKKZGJ0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab\OJSTRFTP\DUEGZWJ0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab\OJSTRFTP\TKQ0CDCA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\acf549ab\OJSTRFTP\W0QSCDCA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I\1Y20B2UN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I\3WKI2A3L
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I\R3MVRXQ1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I\RCFZRXQ1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I\RDLVRHQ1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae61f469\CVLVRG1I\W4VV23MR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae7ea49e
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae7ea49e\EQ1TRFDH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae7ea49e\EQ1TRFDH\TMMOBAFJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae7ea49e\EQ1TRFDH\U33VVMSY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae7ea49e\EQ1TRFDH\XUJOPVS0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ae7ea49e\EQ1TRFDH\XYHCPFS0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7\VS0PJDBU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7\VS0PJDBU\1CA02WJA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7\VS0PJDBU\1OOW2GJA
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7\VS0PJDBU\3KGUFJEQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7\VS0PJDBU\GCWNRLOM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b306fac7\VS0PJDBU\GFT5SWD1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM\2GXDUGYX
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM\AHPVCKPR
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM\BRS5UDHH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM\R2S0Q3MZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM\R32WQNMZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\b9ff0910\UIKTRFTM\RD1WQ3MZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP\JLQHNPLZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP\JUZLNPLZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP\JVXHN5LZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP\QMSIDQDQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP\S3TYDQDQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\bb0e7640\EILFRFLP\ZV1SLVYJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M\0S5NEQVQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M\2P5VEQVQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M\IMQRJ4MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M\ISXRJOMU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M\ITZ3J4MU
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\c8903481\LIKQRG1M\JG25YREJ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N\D4D204DN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N\DAE20ODN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N\DBKQ04DN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N\FB1CWTYC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N\HM0KWDYC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd05049c\MQKRRG1N\JBP5N5O3
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a\CQG5QJDI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a\CQG5QJDI\051WGCT0
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a\CQG5QJDI\S4QVZMFN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a\CQG5QJDI\ULFNKZ54
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a\CQG5QJDI\UPLBKJ54
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cd90aa4a\CQG5QJDI\W4RNZMFN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cf4811cc
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cf4811cc\YWRF3VQZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cf4811cc\YWRF3VQZ\QEM1TXRI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cf4811cc\YWRF3VQZ\TFMDTXRI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cf4811cc\YWRF3VQZ\WEMPTXRI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\cf4811cc\YWRF3VQZ\WGMPTXRI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H\4NIDZFLZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H\BPMZKQ1E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H\BQFVKQ1E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H\BRLZKA1E
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H\K25QHM3J
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\d0465160\WJ1ERE1H\OJ5MHM3J
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c\MXTCRGTL
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c\MXTCRGTL\CO20E5KM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c\MXTCRGTL\DBA2YY31
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c\MXTCRGTL\DFOQYI31
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c\MXTCRGTL\KTQCXHY1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\dba3219c\MXTCRGTL\PNQ4XHY1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c\OHTSREDN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c\OHTSREDN\3DIOGRXF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c\OHTSREDN\3ZQCGRXF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c\OHTSREDN\DAL3RI0G
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c\OHTSREDN\GZ23LDT2
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\de263f5c\OHTSREDN\HAKJRI0G
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd\E1DORFLH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd\E1DORFLH\OFNTFPIZ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd\E1DORFLH\ONYGXTUQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd\E1DORFLH\PBUQRALY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd\E1DORFLH\PF02RQLY
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e1aa56dd\E1DORFLH\PNYOXTUQ
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG\25MEKJFI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG\2MNMJZFI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG\34QNOJQ4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG\354BOZQ4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG\3BZBOJQ4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\e2309f85\CQTVRFDG\SYBVRERM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\0SIEWTNM
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\IOWFAJDF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\J1BW2LKC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\J2BW2LKC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\J5P021KC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\JGOAWED1
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\JQP021KC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\OIXBAZDF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\ed4f3199\FEOSQILM\OLXBAZDF
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN\GNMD2VP4
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN\IJ4QGICB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN\PJ4AGICB
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN\ZOIGCQ13
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN\ZQPGCA13
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f3992d88\EJ1BREDN\ZRBKCQ13
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI\FRETIBXC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI\MT1FAK5R
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI\MY1VAK5R
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI\YIK1NXDH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI\YWN1NHDH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f6008ecf\WUC5RFDI\YXDXNXDH
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP\2YO0G1GC
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP\IHYTUXTD
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP\NPQ3IZ20
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP\XO1CFR53
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP\XQ2CFB53
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\f895b149\KHLTRFDP\XRSOFR53
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP\UJ1SCBEE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP\VAADK34V
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP\XKBA2GBE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP\XP1ODREE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP\XUGA2WBE
C:\ct-raw-scan\De-identified scan images\HCC Surveillance\fb1ac62e\JFKTREDP\XVIM2GBE
